---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks, timer, yaml
      stdout_callback: yaml
verifier:
  name: ansible
